version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pg
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - base-mono
    profiles:
      - dependencies

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/var/lib/redis/data
    networks:
      - base-mono
    profiles:
      - dependencies

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    ports:
      - '3000:3000'
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      NX_DAEMON: 0
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      DATABASE_NAME: pg
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
      - redis
    networks:
      - base-mono

networks:
  base-mono:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
